apiVersion: v1
kind: ServiceAccount
metadata:
  name: mst-driver-container
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mst-driver-container
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - use
  resourceNames:
  - privileged
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mst-driver-container
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mst-driver-container
subjects:
- kind: ServiceAccount
  name: mst-driver-container
userNames:
- system:serviceaccount:mst-driver:mst-driver-container
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mst-driver-container
spec:
  selector:
    matchLabels:
      app: mst-driver-container
  template:
    metadata:
      labels:
        app: mst-driver-container
    spec:
      serviceAccount: mst-driver-container
      serviceAccountName: mst-driver-container
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/mst-driver/mst-driver-container:demo
        name: mst-driver-container
        imagePullPolicy: Always
        command: [sleep, infinity]
        lifecycle:
          postStart:
            exec:
              command: ["modprobe", "-v", "-a" , "simple-kmod", "simple-procfs-kmod"]
          preStop:
            exec:
              command: ["modprobe", "-r", "-a" , "simple-kmod", "simple-procfs-kmod"]
        securityContext:
          privileged: true
      nodeSelector:
        node-role.kubernetes.io/worker: ""
